# Generated by Django 3.0.3 on 2020-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
