# Generated by Django 3.0.3 on 2020-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='USER NAME IS NOT SET', max_length=30),
        ),
    ]
